---
new_page_extension: md
auto_deploy: false
admin_path: public/forestry
webhook_url: 
sections:
- type: directory
  path: events
  label: Events
  create: all
  match: "**/*"
- type: document
  path: _posts
  label: Blogs
- type: directory
  path: workshops
  label: Workshops
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - workshops
upload_dir: static/img/upload
public_path: static/img/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
