---
new_page_extension: html
auto_deploy: false
admin_path: public/forestry
webhook_url: 
sections:
- type: directory
  path: posts/events
  label: Viðburðir
  create: all
  match: "**/*"
  templates:
  - vidburdatemplate
- type: directory
  path: posts/workshops
  label: Listasmiðjur
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - workshops
- type: document
  path: _posts
  label: Blogs
upload_dir: public/img/upload
public_path: img/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
